EESchema Schematic File Version 4
EELAYER 30 0
EELAYER END
$Descr A4 11693 8268
encoding utf-8
Sheet 1 9
Title ""
Date ""
Rev ""
Comp ""
Comment1 "ALL POLARIZED CAPS ARE ELECTROLYTIC"
Comment2 "ALL NON-POLARIZED CAPS ARE X5R 50v RATED (OR BETTER) CERAMIC"
Comment3 "DECOUPLE STANDARD: 1nF 10nF 100nF"
Comment4 ""
$EndDescr
$EndSCHEMATC
